### ISSUE TITLE
Mistake in diagram

### ISSUE THREAD

**Issue by mattagape** [sbgn/sbgn.github.io#5]
Hello there. I am new to SBGN and was just looking at the webpages.

On [this page](https://sbgn.github.io/learning), the example “Protein phosphorylation” says, “A kinase protein catalyzes an irreversible reaction which consumes unphosphorylated protein X and ATP and produces phosphorylated protein X and ADP.”
However, the ATP and ADP are not shown in the diagram. Is that a mistake, or deliberate?
If a mistake, it should be fixed. If it's deliberate, it needs to be explained why.

Thanks
Matthew

**Comment by amazein** [comment]
Thank you, Matthew, the description is fixed now: https://sbgn.github.io/learning. ATP and ADP do participate in this process but since they are not shown we should not put them in the description. In general, because it is the common mechanisms for protein phosphorylation, omitting ATP and ADP allows making signalling diagrams less busy and more readable.
